apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft01
  name: minecraft01
  namespace: minecraft
spec:
  ports:
  - port: 25565
    protocol: TCP
    targetPort: 25565
    nodePort: 30001
  selector:
    app: minecraft01
  type: LoadBalancer
